name: ci

on:
  push:
    branches:
      - master
      - DV-859-automate-tf-docs
  pull_request:

env:
  GO_VERSION: "1.18.3"

jobs:
  build:
    runs-on: [self-hosted, shared]
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build binary
        run: make build
