name: ci

on:
  push:
    branches:
      - master
      - DV-859-automate-tf-docs
  pull_request:

permissions:
  packages: write

env:
  GO_VERSION: "1.18.3"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build binary
        run: make build

      - uses: actions/upload-artifact@v3
        with:
          name: tf-docs-bin
          path: bin/linux-amd64/terraform-docs
