name: ci

on:
  push:
    branches:
      - master
      - DV-859-automate-tf-docs
  pull_request:

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  GO_VERSION: "1.18.3"

jobs:
  build:
    runs-on: [self-hosted, ubuntu-latest]
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build binary
        run: make build

      - uses: recurforever/devops-actions/core/upload-artifacts-s3/v0@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          glob-pattern: bin/linux-amd64/terraform-docs
          s3-artifact-bucket: rc-gbl-tools-artifacts
          s3-artifact-version: "v1"

